### ISSUE TITLE
Checksum fails and libsqlite3.so.3 not found

### ISSUE THREAD

**Issue by hnaparst** [jorgicio/jorgicio-gentoo#15]
The checksum fails, so the ebuild fails to build.

Also,  the ebuild is missing some dependencies.  libsqlite3 is not pulled in.

**Comment by jorgicio** [comment]
What package?

**Comment by hnaparst** [comment]
net-misc/megasync-2.0.0

Kind Regards,

Harold Naparst harold@alum.mit.edu




On Wed, Jun 10, 2015, at 06:46 AM, Jorge Pizarro Callejas wrote:
> What package?


> — Reply to this email directly or view it on GitHub[1].

>


Links:

  1. https://github.com/jorgicio/jorgicio-gentoo/issues/15#issuecomment-110587740

**Comment by jorgicio** [comment]
Fine, I'll check it. Thanks.

**Comment by jorgicio** [comment]
Fixed. Try again, and tell me what's going on :D

**Comment by hnaparst** [comment]
It builds correctly, but at runtime it cannot find libsqlite3.so.0

Kind Regards,

Harold Naparst harold@alum.mit.edu




On Wed, Jun 10, 2015, at 07:04 AM, Jorge Pizarro Callejas wrote:
> Fixed. Try again, and tell me what's going on :D


> — Reply to this email directly or view it on GitHub[1].

>


Links:

  1. https://github.com/jorgicio/jorgicio-gentoo/issues/15#issuecomment-110590311

**Comment by jorgicio** [comment]
That's weird, but I think what's happening. I ran MegaSync on my laptop, and it works fine.
Perhaps you must rebuild Sqlite 3. If problem persists and you have a 64-bit processor, try rebuilding again, but with ABI_X86="32 64 -x32", as I have it built.

**Comment by hnaparst** [comment]
Can you add libsqlite3 as an RDEP

Kind Regards,

Harold Naparst harold@alum.mit.edu




On Wed, Jun 10, 2015, at 07:12 AM, Jorge Pizarro Callejas wrote:
> That's weird, but I think what's happening. I ran MegaSync on my
> laptop, and it works fine.
>
Perhaps you must rebuild Sqlite 3. If problem persists and you have a
64-bit processor, try rebuilding again, but with ABI_X86="32 64 -x32",
as I have it built.

> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/jorgicio/jorgicio-gentoo/issues/15#issuecomment-110591605

**Comment by jorgicio** [comment]
Well... I already put sqlite3 as a RDEPEND in the ebuild ._.

**Comment by hnaparst** [comment]
OK, thanks.  It works now, but with the warnings that no version information is available for libcrypto.so and libssl.so.  Also, have you considered writing a startup script?

**Comment by jorgicio** [comment]
Well... Tried here, and the only warning I have, is this:

 * QA Notice: Pre-stripped files found:
 * /usr/bin/megasync
ecompressdir: bzip2 -9 /usr/share/doc

 * QA Notice: Found an absolute symlink in a library directory:
 *            usr/lib64/libcrypto++.so.9 -> /usr/lib64/libcrypto++.so.0.0.0
 *            It should be a relative symlink if in the same directory
 *            or a linker script if it crosses the /usr boundary.

As a probably 32-bit app, as an advice, rebuild @world with ABI_X86="32 64 -x32". I have all multilib packages with that option in make.conf, and I have no problems at all.

And thanks, I'll consider and research about a startup script.
